### PR TITLE
Ain't go without kind projector

### PR DESCRIPTION
**Pull request by Leammas**
The plugin absence may lead astray

### CODE REVIEW

**Comment by notxcain** [comment]
This section is about essential things required to work with Liberator, which `kind-projector` isn't. Maybe it's better to add it as a side note in the beginning of an example, that `?` syntax is from `kind-projector` with a link to repository?

**Comment by Leammas** [comment]
I see, fixed it.

**Comment by notxcain** [comment]
@Leammas, let's rephrase a little 

The `?` syntax for type lambdas is provided by

**Comment by notxcain** [comment]
Awesome, thanks!

**Pull request merged**
